<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sportschuetzen.Dahl.Disag.Models\Sportschuetzen.Dahl.Disag.Models.csproj" />
    <ProjectReference Include="..\Sportschuetzen.Dahl.Disag.Rm3\Sportschuetzen.Dahl.Disag.Rm3.csproj" />
  </ItemGroup>

</Project>
