name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        push: true
    - name: Build the Docker image
      working-directory: src/Sportschuetzen.Dahl.Disga.Server
      run: docker build . --tag disag-rm3-server:$(date +%s)
